openapi: 3.0.2

info:
  title: AODT Cilckhouse RESTful API
  description: None
  version: 0.0.1

servers:
  - url: http://140.113.144.121:2980

components:
  schemas:
    User:
      type: object
      properties:
        UID:
          type: integer
          example: 1
        account:
          type: string
          example: user1
        password:
          type: string
          example: 1
        email:
          type: string
          example: user1@gmail.com
        salt:
          type: string
          example: asdfghjkl;

tags:
  - name: UE
  - name: foo

paths:
  /User:
    post:
      tags:
        - foo
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User_info'

      responses:
        '201':
          description: Create
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /User/Account/{account}:
    get:
      tags:
        - foo
      summary: Return a user by account
      parameters:
        - name: account
          in: path
          required: true
          schema:
            type: string
            example: user1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found!